spring.application.name=backend

# MongoDB Configuration
spring.data.mongodb.uri=mongodb+srv://nayakraja151:helloMongoDB@cluster0.xzcz0ry.mongodb.net/gforms
spring.data.mongodb.database=gforms

# Server
server.port=${PORT:8080}

# CORS
app.cors.allowed-origins=http://localhost:3000

# Base URL for public form links
app.base-url=http://localhost:3000

# Logging
logging.level.com.raja.backend=DEBUG